version: "3.8"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - "8486:5432"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - demo_bridge
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
    depends_on:
      - postgresql
    volumes:
      - './mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme'
    networks:
      - demo_bridge
  api:
    image: demo:0.0.1-SNAPSHOT
    ports:
      - "8488:8081"
    depends_on:
      - keycloak
      - postgresql
    networks:
      - demo_bridge
    restart: always
volumes:
  postgresql_data:
    driver: local
networks:
  demo_bridge:
    name: demo_bridge
    driver: bridge